### ISSUE TITLE
Wet Savanna heat/humidity change request

### ISSUE THREAD

**Issue by CowboyLva** [Skandarella/naturalbiomes#5]
Current

    heat_point = 65,
    humidity_point = 40,

Recommended

    heat_point = 89,
    humidity_point = 54,

This puts it in values between rainforest 86/65 and savanna 89/40 humidity wise. Extra Biomes Humid Savanna uses the same parameters so I figure it would be useful here. Related: https://en.wikipedia.org/wiki/Biome#/media/File:Vegetation.png
There may be minor adjustments to be done to this in case the Wet Savanna band needs to take more or less territory. That can be nailed by trial and error.

Also it's highly recommended to do a general overview of this mod's relations with vanilla mtg biomes as well.

Vanilla biome list - biome heat/humidity

icesheet 0/73
tundra 0/40
taiga 25/70
snowy grassland 20/35
grassland 50/35
coniferous forest 45/70
deciduous forest 60/68
desert 92/16
sandstone desert 60/0
cold desert 40/0
savanna 89/42
rainforest 86/65

**Comment by Skandarella** [comment]
I have changed the values to: 
    heat_point = 86,
    humidity_point = 60,
This makes it possible not to replace large parts of the MTG Savanna. The Wet Savanna now spawns near Savannas and Rainforests.
This change will be included in the next update in a few days.

**Comment by CowboyLva** [comment]
Ok, nice.
Sorry for the late reply.
