### ISSUE TITLE
Hazelnut Woven Fence overrides glass pane

### ISSUE THREAD

**Issue by shrimpza** [Skandarella/naturalbiomes#6]
In `bushland.lua`, the `xpanes.register_pane("pane", ...` call at the end overrides the standard glass pane from Minetest Game/XPanes.

This can probably be resolved by changing the `"pane"` name to something like `"hazelnut_pane"`.

Not submitting a PR, since it seems you use alternative method of uploading the source files.

**Comment by Skandarella** [comment]
Should be fixed in the new update

**Comment by shrimpza** [comment]
Thank you!
